# Change these first
owner: TacoCompany # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AtomicAssets (AtomicHub)
    url: https://wax.api.atomicassets.io/assets/1099548897666
  - name: Balances API (EOS Amsterdam)
    url: https://lightapi.eosamsterdam.net/api/balances/wax/eosio.token

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tacocrypto.io
  # baseUrl: /upptime
  logoUrl: https://assets.buddywatch.app/taco/logo/ItunesArtwork@2x.png
  name: Taco Status
  introTitle: "Taco API status page"
  introMessage: This is a status page for the APIs used by Taco app
  navbar:
    - title: Status
      href: /
    - title: Taco Website
      href: https://tacocrypto.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
